public enum Multiplier
{
    WCKD = 5000,
    FourLeafClover = 400,
    SkullFour = 50,
    SkullThree = 30,
    CrocodileFour = 50,
    CrocodileThree = 30,
    RavenFour = 20,
    RavenThree = 10,
    OwlFour = 3,
    OwlThree = 2,
    BatFour = 5,
    BatThree = 4,
    MothFour = 3,
    MothThree = 2,
    SpiderFour = 3,
    SpiderThree = 2,
    RoseFour = 3,
    RoseThree = 2,
    LilyPadFour = 2,
    LilyPadThree = 1,
    FlowerFour = 2,
    FlowerThree = 1,
    DeadTreeFour = 2,
    DeadTreeThree = 1,
}